In [2]:
import numpy as np
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [3]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np

<module 'numpy' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

In [3]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [5]:
np.arange(0,25,4)

array([ 0,  4,  8, 12, 16, 20, 24])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((4,4),dtype = str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [13]:
np.zeros((4,4),dtype = bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.ones((4,5),dtype = str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [20]:
np.ones((4,4),dtype = bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [22]:
np.full((3,5),'3')

array([['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3']], dtype='<U1')

In [23]:
np.full((3,3),'michael')

array([['michael', 'michael', 'michael'],
       ['michael', 'michael', 'michael'],
       ['michael', 'michael', 'michael']], dtype='<U7')

In [24]:
#linspace 

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [27]:
np.linspace(0,10,num =50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [28]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [29]:
np.linspace(0,10,51,dtype =int)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [30]:
set(np.linspace(0,10,3))

{0.0, 5.0, 10.0}

In [32]:
set(np.linspace(0,10,51,dtype = int))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [33]:
#eye

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
#random numbers

np.random.rand(1)

array([0.40020161])

In [37]:
np.random.rand(3)

array([0.41540237, 0.16035748, 0.003659  ])

In [38]:
np.random.rand(3,4)

array([[0.16649254, 0.50881981, 0.29665076, 0.88222458],
       [0.20066173, 0.7033881 , 0.73224208, 0.26152547],
       [0.82518821, 0.34325598, 0.33503121, 0.062502  ]])

In [42]:
import matplotlib.pyplot as plt

In [40]:
# randn

np.random.randn(3)

array([ 0.74139167,  2.05688897, -1.03246496])

In [44]:
np.random.randn(5555).std()**2

1.0369211490960069

In [46]:
np.random.randint(1,99,5)

array([49, 57, 92, 34, 66])

In [53]:
np.random.randint(1,99,10)

array([69, 59, 90, 96,  2, 21, 73, 96, 70, 86])

In [51]:
np.random.randint(10,size=10)

array([0, 0, 0, 5, 0, 9, 8, 0, 4, 2])

In [5]:
np.random.randint(5,size=(2,4))

array([[4, 4, 3, 4],
       [1, 3, 1, 3]])

In [59]:
np.random.randint(1,[3,50])

array([ 1, 21])

In [60]:
np.random.randint(1,[3,50,100],size = (5,3))

array([[ 1, 15, 52],
       [ 2, 32, 64],
       [ 2, 20, 97],
       [ 2,  2, 10],
       [ 2, 22, 86]])

In [61]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
ranarr = np.random.randint(0,50,25)
ranarr

array([48, 26, 16, 32, 31, 21, 33, 10, 10,  8, 47, 30, 35, 15, 24,  7, 11,
        3, 30, 17, 21, 28, 31, 11,  7])

In [8]:
ranarr = np.random.randint((5,50))
ranarr

array([ 2, 17])

In [63]:
np.random.randint([1,30,70],100)

array([46, 84, 78])

In [66]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
ranarr = np.random.randint(0,50,24)
ranarr

array([26, 18,  3, 39, 34, 34, 15,  5, 28,  4, 36, 16, 31, 38, 10, 23,  7,
        6,  2,  0, 40, 33, 49,  3])

In [71]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [72]:
ranarr

array([26, 18,  3, 39, 34, 34, 15,  5, 28,  4, 36, 16, 31, 38, 10, 23,  7,
        6,  2,  0, 40, 33, 49,  3])

In [73]:
ranarr.max()

49

In [74]:
ranarr.min()

0

In [75]:
ranarr.argmax()

22

In [76]:
arr.shape

(24,)

In [77]:
arr.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [79]:
arr.shape

(24,)

In [80]:
arr.dtype

dtype('int64')

In [83]:
a=np.random.randint(10,size=5)
a

array([2, 0, 6, 2, 4])

In [ ]:
b=np.full((4,6),5.5,dtype

In [84]:
a.ndim

1

In [89]:
x=np.array([1,2,3])
y=np.array([4,5,6])


In [90]:
z=np.concatenate([x,y])

In [91]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [93]:
# 2d matrix

a = np.array([[1,2,3],
             [4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [94]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
b = np.array([1,2,3,4,5],float)
b[1] 

2.0

In [10]:
y = np.arange(10,21)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
x = np.array(10)
x

array(10)

In [11]:
np.mean(y)

15.0

In [12]:
np.std(y)

3.1622776601683795

In [13]:
np.min(y)

10

In [15]:
np.argmin(y)

0

In [16]:
np.max(y)

20

In [17]:
np.argmax(y)

10